#!/bin/bash
# Begin LSF Directives
#BSUB -P CSC308
#BSUB -W 01:00
#BSUB -nnodes 2
#BSUB -alloc_flags gpumps
#BSUB -J MySweetSim
#BSUB -o MySweetSim.%J
#BSUB -e MySweetSim.%J

#module load pgi/18.4
#module load cuda
module list
set -x
 
date

jsrun -n 2 -c 6 -a 6 -g 6 ./PeleLM2d.gnu.MPI.CUDA.ex inputs.3d
