#!/bin/bash
# Begin LSF Directives
#BSUB -P CSC308
#BSUB -W 02:00
#BSUB -nnodes 1
#BSUB -alloc_flags gpumps
#BSUB -J MySweetSim
#BSUB -o MySweetSim.%J
#BSUB -e MySweetSim.%J

#module load pgi/18.4
#module load cuda
module list
set -x
 
date

##jsrun -n 1 -c 4 -a 4 ./PeleLM2d.gnu.MPI.ex inputs.3d
jsrun -n 6 -c 7 -a 7 ./PeleLM2d.gnu.MPI.ex inputs.3d > out 
